export const cartActionTypes = {
    TOGGLE_DROPDOWN_STATUS: 'TOGGLE_DROPDOWN_STATUS',
    ADD_TO_CART: 'ADD_TO_CART',
    UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
    DELETE_CART_ITEM: 'DELETE_CART_ITEM',
};
